### PR TITLE
Paper

### PR DESCRIPTION
**Pull request by chrstahl**
Minor textual change to the abstract based on reviewer comments.

Also removed the project code from the paper repository for clarity and consistency.

### CODE REVIEW

**Comment by chrstahl** [comment]
@shapiromatron - Not sure if you get pinged on these automatically or not.

**Review by shapiromatron — CHANGES_REQUESTED** [review]
this seems off to me? it looks like it's just deleting everything except the paper, including the source code? https://github.com/chrstahl/peat/tree/2cc297f7b24499b93c325e6f5e960ce3db4c7729

**Comment by shapiromatron** [comment]
If this gets merged into main, it will wipe the code off our main branch?

**Comment by shapiromatron** [comment]
Sorry, I was being dense. It looks like you want to merge this into the paper branch. My bad, changes look good!

**Pull request merged**
